const mongoose = require('mongoose');

const arTargetSchema = new mongoose.Schema(
  {
    orderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Order',
      required: true,
    },
    orderIdString: {
      type: String,
      required: true,
      uppercase: true,
    },
    imageUrl: {
      type: String,
      required: true,
      comment: 'Original uploaded image URL used as AR target',
    },
    imagePublicId: {
      type: String,
    },
    targetFileUrl: {
      type: String,
      comment: 'URL to compiled .mind file for MindAR (generated by compiler)',
    },
    targetFilePublicId: {
      type: String,
    },
    videoUrl: {
      type: String,
      required: true,
      comment: 'Video URL that plays when target is detected',
    },
    videoPublicId: {
      type: String,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    scanCount: {
      type: Number,
      default: 0,
    },
    lastScannedAt: Date,
  },
  {
    timestamps: true,
  }
);

arTargetSchema.index({ orderId: 1 });
arTargetSchema.index({ orderIdString: 1 });

module.exports = mongoose.model('ARTarget', arTargetSchema);
